# Model architecture parameters
input_shape: [30, 64]
num_classes: 2
num_filters: 32
kernel_size: 4
bilstm_units: 128
num_heads: 8
head_size: 64
dense_units: 64
dropout_rate: 0.05
l2_reg: 0.1

# Training parameters
learning_rate: 0.002
batch_size: 128
epochs: 50
early_stopping_patience: 5
reduce_lr_patience: 3

# Data parameters
data_path: "data/"
test_size: 0.2
val_size: 0.1
