dataset:
  csv_paths: []         # fill with paths to dataset CSVs
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
preprocessing:
  min_max: true
  one_hot: true
model:
  input_dim: 100           # replace with actual feature dim per dataset
  conv_filters: 64
  conv_kernel: 3
  pool_size: 2
  bilstm_units: 128
  mha_heads: 4
  dense_units: 64
  dropout: 0.05
training:
  epochs: 50
  batch_size: 128
  lr: 0.002
  lambda_l2: 1e-4
  lambda_contrastive: 0.2
contrastive:
  temperature: 0.1
  pos_cos_threshold: 0.5
  neg_cos_threshold: 0.3
awdv:
  particles: 10
  iterations: 20
  alpha: 0.9
  beta: 0.5
  gamma: 0.1
seed: 42
